# FORGE CONFIG (DO NOT REMOVE!)
include forge-conf/***/before/*;
include forge-conf/***/laralabeler.example.com/before/*;

server {
    http2 on;
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name laralabeler.invokable.net;
    server_tokens off;
    root /home/forge/laralabeler.example.com/current/public;

    # FORGE SSL (DO NOT REMOVE!)
    ssl_certificate /etc/nginx/ssl/domains/***/***/server.crt;
    ssl_certificate_key /etc/nginx/ssl/domains/***/***/server.key;

    # Add 3 locations for the xrpc endpoints
    location /xrpc/com.atproto.label.subscribeLabels
    {
        proxy_pass http://127.0.0.1:7000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /xrpc/tools.ozone.moderation.emitEvent
    {
        proxy_pass http://127.0.0.1:7001;
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Connection "";
    }

    location /xrpc/_health
    {
        proxy_pass http://127.0.0.1:7001;
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Connection "";
    }

    include forge-conf/***/site.conf;
}

# FORGE CONFIG (DO NOT REMOVE!)
include forge-conf/***/after/*;
include forge-conf/***/laralabeler.example.com/after/*;
